connectn.out: main.o board.o win.o turnInput.o
	gcc -g -Wall -Werror -o connectn.out main.o board.o win.o turnInput.o
	
board.o: board.c board.h
	gcc -g -Wall -Werror -c -o board.o board.c
	
main.o: main.c board.h win.h turnInput.h
	gcc -g -Wall -Werror -c -o main.o main.c
	
win.o: win.c win.h 
	gcc -g -Wall -Werror -c -o win.o win.c
	
turnInput.o: turnInput.c turnInput.h
	gcc -g -Wall -Werror -c -o turnInput.o turnInput.c
	
clean:
	rm -f *.o *.out
