connectn.out: main.o board.o game.o turn.o
	gcc -g -Wall -Werror -o connectn.out main.o board.o game.o turn.o
	
board.o: board.c board.h
	gcc -g -Wall -Werror -c -o board.o board.c
	
main.o: main.c board.h game.h turn.h
	gcc -g -Wall -Werror -c -o main.o main.c
	
game.o: game.c game.h
	gcc -g -Wall -Werror -c -o game.o game.c
	
turn.o: turn.c turn.h
	gcc -g -Wall -Werror -c -o turn.o turn.c
	
clean:
	rm -f *.o *.out